--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4 (Debian 15.4-2.pgdg120+1)
-- Dumped by pg_dump version 15.4 (Debian 15.4-2.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: agents; Type: TABLE DATA; Schema: public; Owner: mcp_user
--

INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('be257540-a808-4db4-8c62-c2eacf73fbb0', 'central_orchestrator', 'Central Orchestrator', 'orchestrator', 'active', NULL, '["task_routing", "workflow_coordination"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.31138+00', '2025-11-20 14:52:58.686095+00', NULL, '{"mob_alias": "CESAR Sheppardini", "voice_mode": "third_person", "hierarchy_role": "boss", "specialization": "Boss - Primary Orchestrator"}', 'central', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('ddceda73-2eaf-4156-93c8-64d4904a0544', 'finpsy_orchestrator', 'FinPsy Orchestrator', 'orchestrator', 'active', NULL, '["financial_analysis", "portfolio_optimization", "risk_assessment"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.304969+00', '2025-11-20 14:52:58.6967+00', NULL, '{"mob_alias": "Paulie Gualtieri", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Financial Psychology Coordination"}', 'finpsy', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('ba1e258a-e9c5-4db6-96df-df3856e663b5', 'finpsy_data_collector', 'Data Collector', 'data', 'active', NULL, '["yahoo_finance", "fred_api", "crypto_data"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.309392+00', '2025-11-20 14:52:58.696949+00', NULL, '{"mob_alias": "Christopher Moltisanti", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Data Collection & Processing"}', 'finpsy', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('e398230d-1b9f-4d50-80a8-0e866c9aed60', 'finpsy_sentiment', 'Sentiment Analyzer', 'analysis', 'active', NULL, '["news_sentiment", "social_media", "market_fear_greed"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.309592+00', '2025-11-20 14:52:58.697128+00', NULL, '{"mob_alias": "Silvio Dante", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Sentiment Analysis & Intelligence"}', 'finpsy', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('b7ac8ad5-7acd-4fcc-8e5d-c879a18bf2dc', 'finpsy_forecaster', 'Forecaster', 'prediction', 'active', NULL, '["prophet", "arima", "time_series"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.309709+00', '2025-11-20 14:52:58.697305+00', NULL, '{"mob_alias": "Bobby Baccalieri", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Forecasting & Prediction"}', 'finpsy', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('0784e4d5-7559-4acf-827e-79c115e3f77c', 'finpsy_portfolio', 'Portfolio Optimizer', 'optimization', 'active', NULL, '["mean_variance", "risk_parity", "black_litterman"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.309789+00', '2025-11-20 14:52:58.697487+00', NULL, '{"mob_alias": "Vito Spatafore", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Portfolio Optimization & Strategy"}', 'finpsy', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('fb746c68-0944-487a-92a9-2672444732e3', 'pydini_orchestrator', 'PydiniRed Orchestrator', 'orchestrator', 'active', NULL, '["workflow_automation", "code_generation"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.309881+00', '2025-11-20 14:52:58.697655+00', NULL, '{"mob_alias": "Ralph Cifaretto", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Workflow Orchestration"}', 'pydini', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('61588447-7670-4a80-930e-754850f36768', 'pydini_adapter', 'Workflow Adapter', 'transformer', 'active', NULL, '["n8n_parser", "zapier_parser"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.309976+00', '2025-11-20 14:52:58.697823+00', NULL, '{"mob_alias": "Richie Aprile", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Workflow Transformation"}', 'pydini', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('26e3ad9e-4961-4a47-81f8-c84edecba0fa', 'pydini_generator', 'Code Generator', 'generator', 'active', NULL, '["python_generation", "docker_packaging"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.310084+00', '2025-11-20 14:52:58.697965+00', NULL, '{"mob_alias": "Furio Giunta", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Code Generation"}', 'pydini', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('1a887ed2-5795-4950-9bb6-f510c25543c7', 'lex_orchestrator', 'Lex Orchestrator', 'orchestrator', 'active', NULL, '["legal_analysis", "compliance_checking"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.310155+00', '2025-11-20 14:52:58.698105+00', NULL, '{"mob_alias": "Jimmy Conway", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Legal Analysis Coordination"}', 'lex', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('8876dc35-b7d1-4e60-809b-c61a01e09d9e', 'lex_contract_analyzer', 'Contract Analyzer', 'analysis', 'active', NULL, '["clause_extraction", "risk_identification"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.310267+00', '2025-11-20 14:52:58.698315+00', NULL, '{"mob_alias": "Tommy DeVito", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Contract Analysis & Intelligence"}', 'lex', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('72ffb657-1114-4931-89ea-0621957be772', 'lex_compliance', 'Compliance Checker', 'validation', 'active', NULL, '["regulatory_compliance"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.310431+00', '2025-11-20 14:52:58.698786+00', NULL, '{"mob_alias": "Frankie Carbone", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Compliance & Validation"}', 'lex', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('951bba29-1a4a-4f30-ac72-193da747b9f0', 'inno_orchestrator', 'Innovation Orchestrator', 'orchestrator', 'active', NULL, '["patent_search", "innovation_tracking"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.31052+00', '2025-11-20 14:52:58.698946+00', NULL, '{"mob_alias": "Billy Batts", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Innovation Coordination"}', 'inno', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('2c675761-b6aa-4b0e-993d-9ebd65860223', 'inno_patent_search', 'Patent Search Agent', 'search', 'active', NULL, '["patent_databases", "prior_art"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.310629+00', '2025-11-20 14:52:58.69938+00', NULL, '{"mob_alias": "Tuddy Cicero", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Patent Information Retrieval"}', 'inno', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('c63f9fdf-c13f-4f13-9582-63aa1dae3f75', 'inno_trend_analyzer', 'Trend Analyzer', 'analysis', 'active', NULL, '["technology_trends"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.310702+00', '2025-11-20 14:52:58.69955+00', NULL, '{"mob_alias": "Nicky Santoro", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Trend Analysis & Intelligence"}', 'inno', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('c0aa2b0f-f5d3-4d2a-b0d0-d7c49ff1f61a', 'creative_orchestrator', 'Creative Orchestrator', 'orchestrator', 'active', NULL, '["content_generation", "seo_optimization"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.310768+00', '2025-11-20 14:52:58.699703+00', NULL, '{"mob_alias": "Ace Rothstein", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Creative Coordination"}', 'creative', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('1d285c14-4c84-4b55-9988-cbbdb36c52f1', 'creative_copywriter', 'Copywriter', 'generator', 'active', NULL, '["marketing_copy", "ad_text"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.310855+00', '2025-11-20 14:52:58.69984+00', NULL, '{"mob_alias": "Ginger McKenna", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Content Generation"}', 'creative', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('fa666c44-c830-4c65-a740-315e4f58ee23', 'edu_curriculum', 'Curriculum Designer', 'generator', 'active', NULL, '["learning_paths"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.311023+00', '2025-11-20 14:52:58.705779+00', NULL, '{"mob_alias": "Luca Brasi", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Curriculum Generation"}', 'edu', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('c3394d4f-2d63-4c4c-b129-10f0fb6bdc12', 'gambino_security', 'Gambino Security', 'orchestrator', 'active', NULL, '["threat_detection", "vulnerability_scanning"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.311167+00', '2025-11-20 14:52:58.706701+00', NULL, '{"mob_alias": "Sal Tessio", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Security & Protection"}', 'security', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('2ce2bce3-ae29-4f1a-82c0-7643830c8409', 'jules_protocol', 'Jules Protocol', 'orchestrator', 'active', NULL, '["api_integration", "protocol_translation"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.311245+00', '2025-11-20 14:52:58.706826+00', NULL, '{"mob_alias": "Rocco Lampone", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Protocol Management"}', 'protocol', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('957c4c2c-6945-4c7a-922a-b27df0bfa4f9', 'email_agent', 'Email Communication Agent', 'communication', 'active', NULL, '{"email": true, "user_interaction": true, "collaborative_llm": true}', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-19 05:47:58.371185+00', '2025-11-20 14:52:58.707095+00', NULL, '{"mob_alias": "Moe Greene", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "External Communication"}', NULL, NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('ec018303-8a5c-4d88-9e92-ef9be2b41a8d', 'edu_orchestrator', 'Education Orchestrator', 'orchestrator', 'active', NULL, '["curriculum_design", "adaptive_learning"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.310927+00', '2025-11-20 14:52:58.700875+00', NULL, '{"mob_alias": "Frankie Marino", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Education Coordination"}', 'edu', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('bc581e60-2823-40ff-adaa-237a5d815f96', 'omnicognition', 'OmniCognition', 'orchestrator', 'active', NULL, '["advanced_reasoning", "meta_cognition"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.311093+00', '2025-11-20 14:52:58.705935+00', NULL, '{"mob_alias": "Pete Clemenza", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Multi-Agent Cognition"}', 'omnicognition', NULL);
INSERT INTO public.agents (id, agent_id, name, type, status, version, capabilities, skills, protocols, config, environment, tasks_completed, tasks_failed, success_rate, avg_response_time_ms, uptime_percentage, current_memory_mb, current_cpu_percent, max_concurrent_tasks, current_task_count, endpoint_url, health_check_url, last_heartbeat, last_health_check, created_at, updated_at, created_by, metadata, mcp_system, tenant_id) VALUES ('a6a7a15d-ab89-4061-97ce-276e5237a57c', 'skillforge', 'SkillForge', 'orchestrator', 'active', NULL, '["skill_discovery", "auto_deployment"]', '[]', '[]', '{}', '{}', 0, 0, 0.00, NULL, NULL, NULL, NULL, 5, 0, NULL, NULL, NULL, NULL, '2025-11-18 14:44:51.311306+00', '2025-11-20 14:52:58.70696+00', NULL, '{"mob_alias": "Al Neri", "voice_mode": "third_person", "hierarchy_role": "specialist", "specialization": "Skill Development"}', 'skillforge', NULL);


--
-- PostgreSQL database dump complete
--

